cabal-version:      3.14
name:               attulus
version:            0.1.0.0
description:        RSS feed generator for discogs.com
license:            AGPL-3.0-or-later
license-file:       LICENSE
author:             Boris Stepanov
category:           rss, web
build-type:         Simple
homepage:           https://github.com/boris-stepanov/attulus

common warnings
    ghc-options: -Wall -O0

executable attulus
    import:           warnings
    main-is:          Main.hs
    build-depends:    base ^>=4.21.2.0
                    , aeson
                    , bytestring
                    , crypton-connection
                    , data-default
                    , directory
                    , filepath
                    , http-client
                    , http-client-tls
                    , mtl
                    , text
                    , time
                    , unordered-containers
                    , yaml
    other-modules:    PackageInfo_attulus
    hs-source-dirs:   bin
    default-language: GHC2024
